### ISSUE TITLE
Ambient const enums are not allowed when the '--isolatedModules' flag is provided

### ISSUE THREAD

**Issue by mattp0123** [vercel/swr#1434]
# Bug report

## Description / Observed Behavior

I got these errors from TypeScript compiler after upgrading SWR to 1.0.0

```
node_modules/swr/dist/types.d.ts:80:6 - error TS2748: Cannot access ambient const enums when the '--isolatedModules' flag is provided.

80     [RevalidateEvent.FOCUS_EVENT]: void;
        ~~~~~~~~~~~~~~~

node_modules/swr/dist/types.d.ts:81:6 - error TS2748: Cannot access ambient const enums when the '--isolatedModules' flag is provided.

81     [RevalidateEvent.RECONNECT_EVENT]: void;
        ~~~~~~~~~~~~~~~

node_modules/swr/dist/types.d.ts:82:6 - error TS2748: Cannot access ambient const enums when the '--isolatedModules' flag is provided.

82     [RevalidateEvent.MUTATE_EVENT]: Promise<boolean>;
        ~~~~~~~~~~~~~~~

```

## Expected Behavior

compiled successfully

## Repro Steps / Code Example
tsconfig.json
```json=
{
  "compilerOptions": {
    "isolatedModules": true,
    ...
  }
}
```

## Additional Context

SWR version: 1.0.0
Using vite as the bundler

**Comment by huozhi** [comment]
Close as duplicated with #1420, will be resolved after new version is released 🙏
