### ISSUE TITLE
Missing requestAnimationFrame after upgrading to 0.5.3

### ISSUE THREAD

**Issue by ranisalt** [vercel/swr#1046]
# Bug report

## Description / Observed Behavior

After upgrading from 0.4.2 to 0.5.3, I now get the following error on a specific call of `useSWR`:

`TypeError: 'requestAnimationFrame' called on an object that does not implement interface Window.`

## Expected Behavior

It should load as it did before

## Repro Steps / Code Example

I don't know how to isolate this. Other calls work fine, this works fine too, it breaks after a rerender. Stack trace is useless, it just points that it happens inside `useSWR`, and none of my calls pass `requestAnimationFrame` calls inside useSWR.

## Additional Context

SWR version: 0.5.3

**Comment by ranisalt** [comment]
I just tested that 0.5.2 works fine. The breaking call is [on this specific line](https://github.com/vercel/swr/blob/0.5.3/src/use-swr.ts#L571)

**Comment by huozhi** [comment]
@ranisalt Could you have provide some error trace or a minimal repro on codesandbox to help us identify the issue?

**Comment by huozhi** [comment]
This issue is highly like #1050 but the error message looks slightly different. @ranisalt can you provide any information about the browser you're using? then would be easy to check if they're caused by the same root cause.

**Comment by ranisalt** [comment]
Firefox 86 with the same Parcel 2 bundler they use in #1050 

I highly suspect Parcel to be the culprit as today we had an instance of missing exports in the bundle, it's not the first (nor the second, nor the third...) time and we gave up, moved to Webpack and it was fixed. I need to try swr 0.5.3 tomorrow.

**Comment by huozhi** [comment]
Thank you, I can confirm they're the identical issue with different output from different JS engine now. I'll close this as duplicate of #1050
