### PR TITLE
fix: invalid invocation on raf

### LINKED ISSUE #1046: Missing requestAnimationFrame after upgrading to 0.5.3
# Bug report

## Description / Observed Behavior

After upgrading from 0.4.2 to 0.5.3, I now get the following error on a specific call of `useSWR`:

`TypeError: 'requestAnimationFrame' called on an object that does not implement interface Window.`

## Expected Behavior

It should load as it did before

## Repro Steps / Code Example

I don't know how to isolate this. Other calls work fine, this works fine too, it breaks after a rerender. Stack trace is useless, it just points that it happens inside `useSWR`, and none of my calls pass `requestAnimationFrame` calls inside useSWR.

## Additional Context

SWR version: 0.5.3

### PR DESCRIPTION
**Pull request by huozhi**
Fixes #1046 #1050

### Minimal repro

```js
a = {
   raf: window.requestAnimationFrame,
   raf_pure: f => window.requestAnimationFrame(f)
}

f = () => console.log(1)
a.raf(f) // Error
// Chrome: Uncaught TypeError: Illegal invocation
// Firefox: Uncaught TypeError: 'requestAnimationFrame' called on an object that does not implement interface Window.

a.raf_pure(f) // log `1` in console
```

Possible root cause:

checked the repro in #1050, the line calling rAF is compiled to `c.rAF(n)`, rAF called on an object `c`, which represents a module. We need to make it pure.

### CODE REVIEW

**Review by shuding — APPROVED** [review]
Nice find

**Comment by koba04** [comment]
That's so great! Thank you for your fix!
